trigger:
- main

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'complete/pom.xml'   # <<<<<<--- FIXED LINE
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    mavenVersionOption: 'Default'
    workingDirectory: 'complete'       # Optional, if needed

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'docker'
    repository: 'saibayyana/gs-rest-service'
    command: 'buildAndPush'
    Dockerfile: 'complete/Dockerfile'  # <<<<<<--- FIXED LINE
    tags: |
      latest
      $(tag)
